### ISSUE TITLE
Meteorite explosion collision

### ISSUE THREAD

**Issue by Davidek776** [XRD10/x-wing-vr#46]
Implement explosion that will be triggered when object collides with meteorite.

**Comment by simonfrayer** [comment]
So I have the following thoughts:

When an enemy or an X-Wing collides with the meteorite then they spaceship should explode, meaning it should either stop moving in any direction and add an explosion to it, or we could just remove the object and instantiate an explosion animation for some time instead.

When an enemyor the X-wing collides with the meteorite I think we should have a variable within the script that will be handling the collision that will be a ‘respawn’ boolean, if checked then the objecrt that just crashed should respawn in its original start location, if not checked the object should just be destroyed

**Comment by Davidek776** [comment]
Ok, I understand. Regarding the X-Wing, if it hits the meteorite then it should also stop moving same as enemies? Or there should be just explosion and that's it?

**Comment by JcullenNZ** [comment]
Explosion and some damage I think? Maybe remove the asteroid and deal some damage?
